set(QTQUICK3D_HEADERS_VIEWMODELS

)

source_group("include\\viewmodels" FILES ${QTQUICK3D_HEADERS_VIEWMODELS})

include(${PROJECT_SOURCE_DIR}/include/viewmodels/view3D/view3D.cmake)

set(QTQUICK3D_HEADERS_VIEWMODELS
	${QTQUICK3D_HEADERS_VIEWMODELS}
	${QTQUICK3D_HEADERS_VIEWMODELS_VIEW3D}
)
