set(QTQUICK3D_HEADERS_VIEWMODELS_VIEW3D

)

source_group("include\\viewmodels\\view3D" FILES ${QTQUICK3D_HEADERS_VIEWMODELS_VIEW3D})

include(${PROJECT_SOURCE_DIR}/include/viewmodels/view3D/model/model.cmake)
include(${PROJECT_SOURCE_DIR}/include/viewmodels/view3D/scene/scene.cmake)
include(${PROJECT_SOURCE_DIR}/include/viewmodels/view3D/utility/utility.cmake)

set(QTQUICK3D_HEADERS_VIEWMODELS_VIEW3D
	${QTQUICK3D_HEADERS_VIEWMODELS_VIEW3D}
	${QTQUICK3D_HEADERS_VIEWMODELS_VIEW3D_MODEL}
	${QTQUICK3D_HEADERS_VIEWMODELS_VIEW3D_SCENE}
	${QTQUICK3D_HEADERS_VIEWMODELS_VIEW3D_UTILITY}
)
